### ISSUE TITLE
Y axis mismatch

### ISSUE THREAD

**Issue by sgergo** [apexcharts/vue-apexcharts#146] opened 2019-09-03 16:41 UTC
When using breakpoints the chart won't render correctly and chart values won't be in sync to the Y axis. Screenshots below:

After breakpoint @425, inspector phone mode
![Screenshot from 2019-09-03 18-36-24](https://user-images.githubusercontent.com/7753817/64192188-6659bd80-ce7a-11e9-9e74-81235a85c75d.png)

No breakpoint, normal mode
![Screenshot from 2019-09-03 18-36-48](https://user-images.githubusercontent.com/7753817/64192200-69ed4480-ce7a-11e9-8393-d29cd094d953.png)

**Comment by junedchhipa** [comment] 2019-09-03 19:20
The issue happens when xaxis labels are rotated.
Closing as duplicate of https://github.com/apexcharts/apexcharts.js/issues/718

**Closed by junedchhipa** 2019-09-03 19:20 UTC
