### ISSUE TITLE
After open zoom troubles

### ISSUE THREAD

**Issue by kulkoff** [apexcharts/vue-apexcharts#8] opened 2018-09-13 12:08 UTC
Hi. I'm open my page with 
"<apexcharts width="600px" type="line" :options="chartOptions" :series="sales"></apexcharts> "
![image](https://user-images.githubusercontent.com/13164703/45487427-b6c2a180-b777-11e8-9687-b81d1fcb3506.png)
and see:
![image](https://user-images.githubusercontent.com/13164703/45487283-53387400-b777-11e8-8f1a-82017e1cb3d4.png)
after click "reset zoom" - ok
![image](https://user-images.githubusercontent.com/13164703/45487364-8975f380-b777-11e8-823a-82c73a32e67c.png)
Sorry for my English )

**Comment by junedchhipa** [comment] 2018-09-13 12:17
Can you please paste your full chartOptions object as well as series array?

**Comment by kulkoff** [comment] 2018-09-13 12:30
chartOptions: {
          annotations: {
            xaxis: [{
              x: new Date('01 Jan 2018').getTime(),
              borderColor: '#FEB019',
              label: {
                borderColor: '#FEB019',
                style: {
                  color: '#fff',
                  background: '#FEB019'
                },
                orientation: 'horizontal',
                text: 'Новый год'
              }
            }]
          },
          chart: {
            height: 380,
            type: 'line',
            zoom: {
              enabled: false
            }
          },
          dataLabels: {
            enabled: false
          },
          stroke: {
            curve: 'straight'
          },
          title: {
            text: 'Продажи за последние 12 месяцев',
            align: 'left'
          },
          grid: {
            row: {
              colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
              opacity: 0.5
            }
          },
          xaxis: {
            type: 'datetime',
            max: new Date().getTime(),
            tickAmount: 12
          }
        },

**Comment by junedchhipa** [comment] 2018-09-13 12:40
I cannot reproduce the error on my side with your given config object.

Can you please create a [codepen](https://codepen.io) demo (without Vue.js is fine)?

**Comment by kulkoff** [comment] 2018-09-13 12:43
https://codepen.io/kulkoff/pen/oPyLVb

**Comment by kulkoff** [comment] 2018-09-13 12:47
It's just that without Vue.js, there will not be an error.
Data can be replaced with default ones. If you refresh the page, then everything is ok. But when initializing occurs as in the screenshot

**Comment by junedchhipa** [comment] 2018-09-13 12:49
Ok, please send me the sales series which you have used

**Comment by junedchhipa** [comment] 2018-09-13 12:51
I expected a working example on codepen.
You can also try codesandbox for vue.js which is more convenient than codepen to test Vue applications

**Comment by junedchhipa** [comment] 2018-09-13 12:52
Here is an updated version of your [example](https://codepen.io/apexcharts/pen/JaZRYG) on codepen, can you please fill the required options, and get a working copy? Thanks

**Comment by kulkoff** [comment] 2018-09-13 13:02
updated on codepen 
https://codepen.io/kulkoff/pen/mGKrEB

**Comment by arkhenstone** [comment] 2018-09-13 13:11
It renders okay for me on Vivaldi stable. What browser and version are you using ?

**Comment by junedchhipa** [comment] 2018-09-13 13:19
Not OK on safari.
I suspect the DateTime strings in xAsisTotal array is invalid.
Instead of "Sep 2017", please try "01 Sep 2017" because Safari doesn't understand "Sep 2017"

I need to put a doc with supported datetime accepted by ApexCharts

**Comment by kulkoff** [comment] 2018-09-13 13:46
I'm using chrome

**Comment by junedchhipa** [comment] 2018-09-13 13:55
Ok, which version of ApexCharts you're using?
I released 46 versions in 46 days which is a bit too much looking at the number of fixes I made.

Also, you are never zooming down the chart, right? It is always turned off.
Just the initial render without any data gets weird. Correct?

**Comment by kulkoff** [comment] 2018-09-13 14:32
Yes. And if the data is updated, then the render normally occurs. Later I will say the version

**Comment by junedchhipa** [comment] 2018-09-13 14:35
Ok, then please update to latest version and then test.
Because I fixed the issue already as it was already raised by another user.

**Comment by kulkoff** [comment] 2018-09-13 15:57
![image](https://user-images.githubusercontent.com/13164703/45500221-9b678e80-b797-11e8-88d9-eb8b6df2e589.png)

**Comment by junedchhipa** [comment] 2018-09-13 16:00
Ok, so you're using the latest version 😀 
I will take a look very soon for the issue you reported.

**Comment by kulkoff** [comment] 2018-09-13 16:02
I can give access to my application so that you can see for yourself

**Comment by kulkoff** [comment] 2018-09-13 16:54
The width = 100% does not work yet. It produces an error on the first render. Then refresh ok. This can help somehow in the search for an error

**Comment by kulkoff** [comment] 2018-09-13 16:58
apexcharts.min.js?2227:1 Error: <rect> attribute height: A negative value is not valid. ("-74")

**Comment by kulkoff** [comment] 2018-09-13 16:59
`<apexcharts width="100%" type="line" :options="chartOptions" :series="sales"></apexcharts>`

**Comment by kulkoff** [comment] 2018-09-14 11:29
I think I understood what the problem is. When rendering a page, the parent div has an attribute display:none. I moved to another page and the result was ok

**Comment by junedchhipa** [comment] 2018-09-14 11:30
Thank you 😀 
Can we close this now?

**Comment by kulkoff** [comment] 2018-09-14 11:36
yes. Thank you

**Closed** 2018-09-14 11:37 UTC
