### ISSUE TITLE
TypeError: ApexCharts.merge is not a function

### ISSUE THREAD

**Issue by Dan-Shields** [apexcharts/vue-apexcharts#64] opened 2019-02-23 02:13 UTC
I'm get the following error in browser console:
```
TypeError: ApexCharts.merge is not a function
    at VueComponent.init (vue-apexcharts.js:84)
    at VueComponent.mounted (vue-apexcharts.js:36)
```

I'm using the latest release, and have tried with the latest ApexCharts as well as `^3.0.0` as dictated by the peer dependency.

I can get around this issue by modifying `ApexCharts.component.js` line one to be:

`import ApexCharts from '../../apexcharts/src/apexcharts';`

And then also importing vue-apexcharts directly from src rather than dist in my component:

`import VueApexCharts from '../../node_modules/vue-apexcharts/src';`

**Comment by junedchhipa** [comment] 2019-02-26 03:56
I have released a new version `vue-apexcharts@1.3.0`
Can you please confirm if the latest version doesn't throw this error?

**Comment by Dan-Shields** [comment] 2019-02-26 16:12
I've updated to that version and that specific error has stopped, but now I'm getting a new error when creating the component:
```
TypeError: this.chart.render is not a function
    at a.init (ApexCharts.component.js:83)
    at a.mounted (ApexCharts.component.js:30)
```

And a this error when I update `this.chartSeries`:
```
TypeError: this.chart.updateSeries is not a function
    at a.$watch.t (ApexCharts.component.js:45)
```

**Comment by junedchhipa** [comment] 2019-02-26 18:33
Can you I your code? If possible, please create a codesandbox demo so I can easily reproduce.

**Comment by junedchhipa** [comment] 2019-02-27 13:07
OR
Is it possible for you to zip your project and send it to `juned.chhipa (at) gmail (dot) com` ?
I cannot reproduce the bug easily and would like to directly work in your environment.

**Comment by Dan-Shields** [comment] 2019-02-27 13:10
Sorry I've been busy with other things recently. I can't send you the project but I'll make a codesandbox reproduction later today if I have time.

**Comment by junedchhipa** [comment] 2019-02-27 13:11
Codesandbox would work fine. Thanks

**Comment by junedchhipa** [comment] 2019-04-09 09:12
Duplicate of #88

**Closed by junedchhipa** 2019-04-09 09:12 UTC
Labels: bug

**Comment by UltraCakeBakery** [comment] 2019-07-24 09:18
This issue is back in my latest project. 
The code is a copy of what's in the readme. It also happens when i try and implement the native version of Apex Charts.

**Comment by junedchhipa** [comment] 2019-07-24 09:43
Please create a [codesandbox](https://codesandbox.io/s/pwwz8009n0) demo of the issue you are facing.

**Comment by jessecrossley** [comment] 2020-06-24 19:29
The codesandbox [template ](https://codesandbox.io/s/pwwz8009n0) is no longer working.  I forked the old template and updated the dependencies [here](https://codesandbox.io/s/broken-vue-apexcharts-example-1in4i) (to match what I'm using in my main project and other codesandbox demos) but still getting the "is not a function" errors.
Note that my main project still works; presumably something has changed at codesandbox, but I'm not sure what.

**Comment by junedchhipa** [comment] 2020-06-24 20:02
@jessecrossley Thanks for letting me know.
Somehow, the codesandbox stopped working without any reason and after playing with different Vue versions, it has started to work again.

**Comment by jessecrossley** [comment] 2020-06-24 20:15
Which versions worked? We're using the last "stable" version (Vue 2.6.11) and I cannot get any vue-apexcharts sandboxes to work with latest apexcharts and vue-apexcharts versions.  Using this [test harness](https://codesandbox.io/s/apexcharts-and-vue-pkbq5), I can get charts working, but that's using vue-apexcharts 1.3.6!
