### ISSUE TITLE
Apexcharts data is not shown initially and after refresh

### ISSUE THREAD

**Issue by vhniii** [apexcharts/vue-apexcharts#185] opened 2019-12-07 21:57 UTC
I have vue application where data is passed to apexchart from vuex. 
The problem is with displaying data on chart while initially going to a page which uses the component where apexchart is used. 
If I go back to home page and then back to the page where the chart is then data is showing. but after refresh data is again not showing. 
`
My component:
```
<template> 
     <div>
        <div class="item-chart">
            <apexcharts type="area" class="apexChart" width="100%" height="400px" :options="chartOptions" :categories="categories" :series="series"></apexcharts>
        </div>

        <div class="btn-back">
            <router-link to="/">Back</router-link>
        </div>
    </div>
</template>

<script>
import VueApexCharts from "vue-apexcharts";

export default {
    name: 'currency',
    components: {
        apexcharts: VueApexCharts
    },
    data() {
        return {
            chartOptions: {
                chart: {
                    id: 'chart',
                    toolbar: {
                        show: false
                    }
                },
                xaxis: {
                    categories: [],
                    labels: {
                        style: {
                            colors: '#F1C40F'
                        }
                    }
                },
                yaxis: {
                    show: false
                },
                dataLabels: {
                    enabled: false
                },
                colors: ['#F1C40F']
            },
            series: [{
                name: 'Price',
                data: this.$store.state.currencyHistory.BTC.map(i => i.close),
            }]
        }      
    },
    created() {
        this.getCryptoCurrencyData()
        this.getCurrencyHistory()
        this.chartOptions.xaxis.categories = this.Times
    },
    methods: {
        getCryptoCurrencyData() {
            this.$store.dispatch('getCryptoData')
        },
        getCurrencyHistory() {
            this.$store.dispatch('getCurrencyHistory')
        },
        getChartPrices() {
            this.currencyHistory.BTC.map(i => i.close)
        },
        getChartTimes() {

            const data = [];
            this.$store.state.currencyHistory.BTC.map(i => {
                let time = new Date(i.time * 1000);
                data.push(time.toLocaleString('en-US', { hour: 'numeric', hour12: true}))
            })

            return data;
        }
    },
    computed: {
        cryptoCurrencyData() {
            return this.$store.getters.showCryptoData
        },
        currencyHistory() {
            return this.$store.getters.showCurrencyHistory
        },
        Times() {
            return this.getChartTimes()
        }
    }
}
</script>

```

Also why I canno't give data from vuex store to apexchart with getters, its just not working. (I have to use "this.$store.state").

I would like to know how to fix the problem where data will be showed every time (even if I go to the page first time after running the app) and also showed after refresh.

Thank you in advance

**Comment by woutvw** [comment] 2020-02-27 18:17
I have the same problem, the chart only shows when I resize the browser.
Have you found a sollution already?

**Comment by theDevelopper** [comment] 2020-05-15 13:43
Any updates on this one. I have the same issue with line charts. My line charts are not drawing until I resize the browser. Other chart types like bar and pie work fine.

**Comment by firedev** [comment] 2020-06-11 17:50
I got it to work by triggering `window.resize` manually after updating `series`:

```js
      window.dispatchEvent(new Event('resize'))
```

**Comment by wirakw2** [comment] 2020-08-06 04:09
@firedev how you trigger it ?

**Comment by KayJay89** [comment] 2020-08-12 11:29
> @firedev how you trigger it ?


For use with Vuex (not sure this is what you need though), you can use @firedev's solution by including

```javascript
window.dispatchEvent(new Event('resize'))
```

in your mutation like so:
```javascript
NAME_OF_MUTATION: (state, dataToAdd) => {
      state.nameOfDataInStore = dataToAdd;
      window.dispatchEvent(new Event("resize"));
    },
```

I'm doubtful this a good practice but this is the only way I could get the charts to update using Vuex.

**Comment by FelixWaigner** [comment] 2020-10-15 15:50
Any solutions on this problem yet?

**Comment by theolevisage** [comment] 2020-10-20 07:02
@KayJay89 Which doc are you referring to please ?  I can't find that bit in the apex chart doc in the Vue.js section or even in the updateChart part...

I'm still having this issue and I have to resize to get the data, I'm using the Vuex and I don't see where I'm doing wrong (although there is probably a lot I'm doing wrong haha)

My chart options and series are fully in the vuex and I'm just inserting them into my apexchart component with mapGetters but my chart is empty on load and doesn't update the data after I mutated the state. 

If anybody has a solution that would be great.

**Comment by ridwankustanto** [comment] 2021-01-21 10:11
> ```js
> window.dispatchEvent(new Event('resize'))
> ```

Thanks! It works for me

**Comment by Herant** [comment] 2021-02-17 22:15
Is there really no other way to make charts reactive than to call resize event?

**Comment by gdagrech** [comment] 2021-02-26 13:17
The only way I could solve the problem of rendering an empty board even when the child receives the info was by adding an ngIf directive.
![image](https://user-images.githubusercontent.com/31541831/109304954-ca650400-781b-11eb-9ccf-656b83bec39e.png)

That way it doesnt matter how many time you refresh the page it will always render the chart correctly

**Comment by otherperspectives** [comment] 2021-04-13 19:13
window.dispatchEvent(new Event('resize'))

This workes like a charm.
Thanks!!!

**Comment by Jalgoczy** [comment] 2021-05-15 05:13
I have the same issue on Angular. I load the data asynchronously and the chart starts drawing then shows the noData text. 
A window resize event does not help.

Any other hacks until the issue is resolved?

**Comment by DennisMwongera** [comment] 2021-08-25 14:35
My Chart renders for a sec then disappears, when I switch the view tab to a bar chart once I return to the donut chart it renders well

**Comment by drewm1192** [comment] 2021-08-29 21:12
@DennisMwongera This is exactly what is happening to me with a radial bar chart and I cannot figure out why. I would have assumed the issue is with getting the data when componentDidMount() runs, but the other visuals populate with the same dataset, so it has to be an Apex issue... (I'm using React).

**Comment by 5Sense-PhuocLoiTran** [comment] 2021-08-30 02:00
Any solutions on this problem when refresh yet?

**Comment by DennisMwongera** [comment] 2021-08-30 03:56
When Using React, try giving your series Array some data to work with like series: [ 1, 1, 1, 1, 1 ] this will communicate to the chart there is some data to work with until the store loads up the data and updates your series(React) @drewm1192 @5Sense-PhuocLoiTran

**Comment by DennisMwongera** [comment] 2021-08-30 03:56
For me am using Vue still trying to figure out a way through

**Comment by selfprogrammed** [comment] 2021-11-19 10:45
> When Using React, try giving your series Array some data to work with like series: [ 1, 1, 1, 1, 1 ] this will communicate to the chart there is some data to work with until the store loads up the data and updates your series(React) @drewm1192 @5Sense-PhuocLoiTran

This worked for me perfectly! Thank you so much!

**Comment by cflurin** [comment] 2021-11-23 14:43
I had a similar issue with the latest `apexcharts` version 3.30.0, downgrating to v3.22.2 solved the issue for me.

**Comment by MinSomai** [comment] 2021-11-28 08:29
I have been using keys in each chart component to force render. It was working fine.

As alternative, this also works. downgraded apexcharts and vue-apexcharts to these versions.
I tried downgrading only one of them and the problem persists.
   
 `"apexcharts": "3.24.0",`
 `"vue-apexcharts": "1.5.3"`,

**Comment by cflurin** [comment] 2021-11-28 10:36
Here my latest working versions:

`apexcharts v3.29.0`
`vue-apexcharts v1.62`

**Comment by cflurin** [comment] 2021-11-29 07:57
> I have been using keys in each chart component to force render. It was working fine.

Hi, how did you use keys, can you post an example.

**Comment by MinSomai** [comment] 2021-11-29 08:45
> Hi, how did you use keys, can you post an example.

set key
`
<apexchart :key="testKey"/>
`

data
`
testKey = 1;
`

update options/series then change testKey like so, and it will force render the component 
`
testKey++;
`

**Comment by cflurin** [comment] 2021-11-29 08:54
Thanks, I tried a similar approach (new_data) but it didn't work with apexcharts v3.30.0

**Comment by MinSomai** [comment] 2021-11-29 10:27
> Thanks, I tried a similar approach (new_data) but it didn't work with apexcharts v3.30.0

you have to manually trigger key change `testKey++` after you load options and series.

you can try refresh too.
like this

`
<apexchart ref="myChart"/>
`

manually, somewhere in your method
`
this.$refs.myChart.refresh()
`

**Comment by cflurin** [comment] 2021-11-29 11:17
Okay, I'll try. Anyway with v3.29.0 works for me without any additional code.

**Comment by Soban3** [comment] 2021-11-30 19:47
I know this is old, but I just wanted to leave it here in case someone is lost. I just had a similar issue that the chart was only showing data when I resized the browser. Here is how I solved it for my use case through experimentation and some help from the documentation. First, add a ref on `apexcharts` component.

`<apexcharts type="area" ref="apexChart" class="apexChart" width="100%" height="400px" :options="chartOptions" :categories="categories" :series="series" />`

then call [updateSeries](https://apexcharts.com/docs/methods/#updateSeries) or [updateOptions](https://apexcharts.com/docs/methods/#updateOptions) or both depending upon the use case. 

`this.$refs.apexChart.updateSeries(this.response.series);`
`this.$refs.apexChart.updateOptions({
        xaxis: {
          categories: this.response.labels,
        }
      })` 

on the page visit or whenever the data is not loading basically. I had to do it in `watcher` since in my case the data was not updating after an API call. But, I have not tested this with the router. 

Version: 3.31.0

**Comment by rognales** [comment] 2022-01-15 06:41
This is still happening. I have to pinned to 3.29 as shared to resolved this.

**Comment by greenyboiz** [comment] 2022-01-24 07:39
`<div style="margin-left: -14px" v-if="!isEmpty">
      <VueApexCharts height="240" :options="chartOptions" :series="series" />
    </div>
    <div style="margin-left: -14px" v-else>
      <VueApexCharts height="240" :options="chartOptions" :series="ratioEmpty" />
    </div>`
at else case, it still doesnt render anything iniatially, (my "ratioEmpty" contains object {x: '70', y: 0} )

**Comment by MinSomai** [comment] 2022-01-24 12:36
> `<div style="margin-left: -14px" v-if="!isEmpty"> <VueApexCharts height="240" :options="chartOptions" :series="series" /> </div> <div style="margin-left: -14px" v-else> <VueApexCharts height="240" :options="chartOptions" :series="ratioEmpty" /> </div>` at else case, it still doesnt render anything iniatially but when resize the window, it goes, (my "ratioEmpty" contains object {x: '70', y: 0} ). Please help me out this case :((

from your comment this is what I think is the issue. `series` (ratioEmpty in your case) takes an array and not an object.

examples:
```js
series: [{
          name: 'series-1',
          data: [30, 40, 35, 50, 49, 60, 70, 91]
        }]
```
or
```js
series:[{
  data: [23, 34, 12, 54, 32, ... , 43]
}]
```
or
for pie charts
```js
series: [23, 11, 54, 72, 12],
```

**Comment by greenyboiz** [comment] 2022-01-25 02:48
> > `<div style="margin-left: -14px" v-if="!isEmpty"> <VueApexCharts height="240" :options="chartOptions" :series="series" /> </div> <div style="margin-left: -14px" v-else> <VueApexCharts height="240" :options="chartOptions" :series="ratioEmpty" /> </div>` at else case, it still doesnt render anything iniatially but when resize the window, it goes, (my "ratioEmpty" contains object {x: '70', y: 0} ). Please help me out this case :((
> 
> from your comment this is what I think is the issue. `series` (ratioEmpty in your case) takes an array and not an object.
> 
> examples:
> 
> ```js
> series: [{
>           name: 'series-1',
>           data: [30, 40, 35, 50, 49, 60, 70, 91]
>         }]
> ```
> 
> or
> 
> ```js
> series:[{
>   data: [23, 34, 12, 54, 32, ... , 43]
> }]
> ```
> 
> or for pie charts
> 
> ```js
> series: [23, 11, 54, 72, 12],
> ```

thanks for your reply, actually, my ratioEmpty is an array contains some of that object like that to handle null value of y-axis.

**Comment by rodpatulski** [comment] 2022-04-01 01:24
This is also an issue with reactapexcharts

**Comment by pradeepbp1310** [comment] 2022-04-06 06:25
I was also facing the same issue, fixed it by using a toggle variable which the initial value isChartLoading = false and make it true after updating the series.
```
<ng-container *ngIf="isChartLoading">
      <apx-chart
        [series]="chartOptions.series"
        [chart]="chartOptions.chart"
        [colors]="chartOptions.colors"
        [labels]="chartOptions.labels"
        [legend]="chartOptions.legend"
        [dataLabels]="chartOptions.dataLabels"
        [plotOptions]="chartOptions.plotOptions"
        [stroke]="chartOptions.stroke"
        [responsive]="chartOptions.responsive"
        [tooltip]="chartOptions.tooltip"
      >
      </apx-chart>
</ng-container>
```

**Comment by Bouafia19** [comment] 2022-06-29 14:44
update the whole chart object for both options and series like this:
updateCharte(categories, data){
            this.chartOptions = {
                ...this.chartOptions,
                xaxis: {
                    ...this.chartOptions.xaxis,
                    categories: categories
                } 
            }

            this.chartSeries = [{
                ...this.chartSeries,
                data: data
            }]
        },

**Comment by BayBreezy** [comment] 2022-08-04 02:09
In order to get my charts to render after I leave a page and return, I had to use `setTimeout` in the `mounted hook` in Nuxt 3.

```js
<script setup>
	const setChart = ref(false);
	onMounted(() => {
		setTimeout(() => {
			this.setChart = true;
		}, 100);
	});
</script>
```

Then in the template, I use v-if

```html
<div v-if="setChart" class="grid grid-cols-1 lg:grid-cols-2 gap-10">
	<ChartBar />
       <ChartColumn />
</div>
```

package versions

```json
"dependencies": {
    "@headlessui/vue": "^1.6.7",
    "apexcharts": "^3.35.4",
    "vue3-apexcharts": "^1.4.1"
  }
```

**Comment by mhkarimi1383** [comment] 2022-08-11 20:47
+1

**Comment by mhkarimi1383** [comment] 2022-08-11 21:47
> I got it to work by triggering `window.resize` manually after updating `series`:
> 
> ```js
> window.dispatchEvent(new Event('resize'))
> ```

I have put this into mounted function but for me it was not working

**Comment by fernandolangaro** [comment] 2022-10-09 19:38
For those using Nuxt3 and vue3-apexcharts, that's how I choose to make it work. I added a ":key" prop to my apexchart component
```js
<apexchart
    id="consultasChart"
    :key="renderChart"
    height="300"
    type="bar"
    :options="chartOptions"
    :series="series"
  />
```

And then I set it to update on mounted event
```js
const renderChart = ref(0)
onMounted(() => {
  setTimeout(() => { renderChart.value++ }, 100)
})
```

I made it this way because I think it is better then using a `v-if` condition that will make your page renders first with an empty space and then, just later, suddenly render your apexchart. It is kinda ugly. Hope my solution helps! 🚀

**Comment by GabyRibeiroCode** [comment] 2022-10-24 19:29
I am facing the same problem, please could you reopen the issue. I have tried many solutions including resize.
My versions are apexcharts 3.36.0 and ng-apexcharts 1.7.4.

**Comment by SungJunHan** [comment] 2022-11-08 15:51
In my case the resizing doesn't work. So I found another solution using "watch" as below.
 hope my solution be help

``` 
<apexchart :key="apexKey"  :serises="chartData" ~~~/>  

watch:{
   chartData:{
      deep: true,
      handler() {
        this.apexKey++
      },
    }

**Comment by rodpatulski** [comment] 2022-11-08 21:24
> In my case the resizing doesn't work. So I found another solution using "watch" as below. hope my solution be help
> 
> ```
> <apexchart :key="apexKey"  :serises="chartData" ~~~/>  
> 
> watch:{
>    chartData:{
>       deep: true,
>       handler() {
>         this.apexKey++
>       },
>     }
> ```

What's this 'watch' thing? It's not part of apexchart docs.

**Comment by Arabath** [comment] 2022-11-10 12:01
Excelente,

**Comment by Arabath** [comment] 2022-11-10 12:03
La solucion anterior funciona de maravillas, pero actualiza a una grafica standard, y no respeta los seteos del data. Por ejemplo , si queremos cambiar los colores, tamaño del grafico serado o ocultar los legend que aparecen al lado de la grafica. Hay alguna solucion

**Comment by ianyxtan** [comment] 2023-03-29 23:00
> > Thanks, I tried a similar approach (new_data) but it didn't work with apexcharts v3.30.0
> 
> you have to manually trigger key change `testKey++` after you load options and series.
> 
> you can try refresh too. like this
> 
> `<apexchart ref="myChart"/>`
> 
> manually, somewhere in your method `this.$refs.myChart.refresh()`

Worked like a charm. Thanks for sharing!

**Comment by anantgna** [comment] 2023-06-27 09:36
This issues exists still now, pleases resolve this.

**Comment by EdwinJMataH** [comment] 2023-07-11 22:03
En mi caso hago uso de Vue 3 y los datos pasan a apexchart desde un store de pinia. La forma en como  evito ese problema es haciendo un v-if y verificando que haya información en la variable, muestro un ejemplo en rasgos generales de como esta el código.
  
  import { useDashboardStore } from 'La ruta';
  const useStore = useDashboardStore();
  useStore.getData();
  
  <div v-if="useStore.totales.length > 0"> 
      <VueApexCharts
         type="pie"
         height="410"
         :options="chartOptions"
         :series="useStore.totales"
       />
 </div>

**Comment by sujith-sairam** [comment] 2023-07-12 10:05
When I resize the window the chart works properly or else its not working in angular

**Comment by smitsonani77** [comment] 2023-07-13 16:04
@sujith-sairam if you get any solution in angular then please post here.

**Comment by sujith-sairam** [comment] 2023-07-17 05:52
> @sujith-sairam if you get any solution in angular then please post here.

I found the solution . I tried to  render the chart before it is being assigned to the property chartOptions .Try this solution in your html template

                <ng-container *ngIf="chartOptions">
                          <apx-chart
                            [series]="chartOptions.series"
                            [chart]="chartOptions.chart"
                            [dataLabels]="chartOptions.dataLabels"
                            [plotOptions]="chartOptions.plotOptions"
                            [xaxis]="chartOptions.xaxis"
                            [stroke]="chartOptions.stroke"
                          ></apx-chart>
                        </ng-container>

**Comment by ujaandas** [comment] 2023-09-02 15:18
I'm using React and I have a useEffect() which plots the graph, and it runs anytime the props are changed (ie; the data being fed into the graph) - tried the window resize fix but it only works half the time, any other ideas?

**Comment by smitsonani77** [comment] 2023-09-22 14:45
Can anyone guide me for light/dark theme implementation on dashboard in
angular. Like based on theme I want change the color of all the charts
available on dashboard.

**Comment by IlCallo** [comment] 2023-09-25 12:02
@smitsonani77 your question have nothing to do with this issue, please do not post it here

**Comment by NigmetAli** [comment] 2023-09-28 10:54
> I got it to work by triggering `window.resize` manually after updating `series`:
> 
> ```js
> window.dispatchEvent(new Event('resize'))
> ```

Worked for me, thanks.

**Comment by Mahadi92** [comment] 2023-10-25 08:58
I fix this issue in react.

The following code should be given in the component in which the chart has been made.
```
  useEffect(() => {
    window.dispatchEvent(new Event('resize'))
  },[])
```

**Comment by VanThuan3010** [comment] 2024-01-13 08:57
I fix this issue in javascript.
chart: {
    id: undefined,
    edrawOnWindowResize: false,
    redrawOnParentResize: false 
},

**Comment by lord007tn** [comment] 2024-01-25 11:24
in vue 3 composition api 
i referenced the apexchart and caused a render manually in a watchEffect

```

watchEffect(async () => {
// call whatever function to update your options and series
  if (weightOverTimeRef.value) {
    series.value = [
      {
        name: t('weights'),
        data: weightOverTimeRef.value.weights
      }
    ]
    chartOptions.value = {
      xaxis: {
        type: 'datetime',
        categories: weightOverTimeRef.value.dates
      }
    }
  }
  if (chartRef.value) {
    await chartRef.value?.render()
  }
})
```

```
 <VueApexCharts ref="chartRef" type="area" height="388px" :options="chartOptions" :series="series"></VueApexCharts>
```

the solutions above of dispatching resize event works because they force a re-render in the chart.
so the problem seems to be in how the chart re-renders i didn't go any further but I believe @IlCallo did a great job explaining it 

i don't have time now to investigate more and fix it so it would be a great help to the community if anyone did.

**Comment by syed-rajib** [comment] 2024-03-21 15:49
![Screenshot from 2024-03-21 21-38-54](https://github.com/apexcharts/vue-apexcharts/assets/155349042/46291010-0785-438d-a653-d52008b65dbb)
when dynamically load data in the chart , column not showing as perfectly with yaxis data label . as you can see when hover it value is showing 1182 but Problem is browse column not perfect as y-axis data labels . 

here I am sharing codes. 

           <apexchart
                    ref="barChart"
                    width="100%"
                    type="bar"
                    :options="itemBarChart"
                    :series="[{ data: itemChartData }]"
                  ></apexchart>
                  
                  
                    itemBarChart: {
        chart: {
          type: "bar",
          height: 400,
          toolbar: {
            // show: false,
            show: true,
          tools: {
            download: true,
            selection: true,
            zoom: true,
            zoomin: true,
            zoomout: true,
            pan: true,
            reset: true | '<img src="/static/icons/reset.png" width="20">',
            customIcons: []
          },
          autoSelected: 'zoom'
          },
        },
        colors: ["#008FFB", "#FF4560", "#33B2DF", "#00E396"],
        plotOptions: {
          bar: {
            horizontal: false,
            columnWidth: "55%",
            endingShape: "rounded",
            dataLabels: {
      position: 'bottom'
    }
          },
        },
        dataLabels: {
          enabled: false,
        },
        stroke: {
          show: true,
          width: 2,
          colors: ["transparent"],
        },
        xaxis: {
          categories: [
            "Browse",
            "Positive Rated",
            "Negative Rated",
            "Purchase",
          ],
          labels: {
            style: {
              colors: "#000000",
              fontSize: "14px",
              fontFamily: "Helvetica, Arial, sans-serif",
            },
          },
        },
        yaxis: {
    logarithmic: true,  // Enable logarithmic scale
    // tickAmount: 'dataPoints',  // Adjust the number of ticks for better visualization
    // min: 1,  // Set the minimum value to 1 (or a small value close to your smallest data point)
    // forceNiceScale: false  // Disable the nice scale to ensure we can use a logarithmic scale
  },
        fill: {
          opacity: 1,
        },
        tooltip: {
          x: {
            formatter: function () {
              return "";
            },
          },
          y: {
            formatter: function (val, { dataPointIndex, w }) {
              const label = w.globals.labels[dataPointIndex];
              return `${label}: ${val}`;
            },
            title: {
              formatter: function () {
                return "";
              },
            },
          },
          followCursor: true,
        },
        title: {
          text: "Items Counts",
          align: "center",
          margin: 20,
          style: {
            fontSize: "20px",
            fontFamily: "Helvetica, Arial, sans-serif",
            color: "#333333",
          },
        },
        responsive: [
          {
            breakpoint: 768,
            options: {
              chart: {
                height: 300,
              },
              xaxis: {
                labels: {
                  style: {
                    fontSize: "12px",
                  },
                },
              },
              yaxis: {
                min: 0,
                max: 100,
                labels: {
                  style: {
                    fontSize: "12px",
                  },
                },
              },
              title: {
                style: {
                  fontSize: "16px",
                },
              },
            },
          },
        ],
      },
      
        itemChartData() {


      const x = [
        this.insights.kpi_summary.browse.total_browsed_items,
      this.insights.kpi_summary.ratings.total_positive_rated_items,
      this.insights.kpi_summary.ratings.total_negative_rated_items,
     this.insights.kpi_summary.purchase.total_purchased_items,
      ];
      if (x.length == 4){

        return x;
      }
},

**Comment by anon-phantom** [comment] 2024-08-04 18:55
not familiar with vue, I was looking for a solution in ReactJS to update data series dynamically.

best way to do it is to use `useState` + `useEffect` for a functional component

```jsx
const [records, setRecords] = useState([]);

useEffect(() => {
  setRecords({});
}, [records]);

const series = [
  {
    data: [...records],
    name: 'Records',
  },
];

...

return (
  <ReactApexChart
    id='records-chart'
    options={options}
    series={series}
    type='area'
    height='280px'
  />
);
```

or use `componentDidMount` if you were using a class component, following the same logic.

**Closed** 2024-10-12 14:30 UTC
Labels: no-issue-activity
