### ISSUE TITLE
Apexcharts are not working in laravel 5.5

### ISSUE THREAD

**Issue by odhikari** [apexcharts/vue-apexcharts#40] opened 2019-01-09 19:55 UTC
I have install apexcharts and when I try to create a chart in component it gives an error as below :

**Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not callable**

Let me know if anyone have faced this issue.

Thanks in Advance

**Comment by junedchhipa** [comment] 2019-01-13 06:00
Duplicate of #38

**Closed by junedchhipa** 2019-01-13 06:00 UTC
