### ISSUE TITLE
chart export to PNG include the axis hairlines

### ISSUE THREAD

**Issue by alimjoudeh** [apexcharts/vue-apexcharts#160] opened 2019-10-06 06:41 UTC
when exporting charts to PNG, the axis hairlines are visible on the exported image both on x/y axis, even after updating to the latest version

**Comment by junedchhipa** [comment] 2019-12-24 10:34
Fixed it in the latest version v3.11.2
Duplicate of https://github.com/apexcharts/apexcharts.js/issues/1140

**Closed by junedchhipa** 2019-12-24 10:34 UTC
